### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skf-funzt**
I've updated the documentation based on the solution from issue #144 

### Changelog
doc(README): added note about adding support for other files like .ts

### CODE REVIEW

**Comment by skf-funzt** [comment]
> ###  No Changeset found
> Latest commit: [ab24747](https://github.com/ota-meshi/eslint-plugin-astro/commit/ab24747abf112d87529c51e160ee83ebe1866b84)
> 
> Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**
> 
> This PR includes no changesets
> [Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).
> 
> [Click here if you're a maintainer who wants to add a changeset to this PR](https://github.com/skf-funzt/eslint-plugin-astro/new/patch-1?filename=.changeset/dirty-hounds-brush.md&value=---%0A%22eslint-plugin-astro%22%3A%20patch%0A---%0A%0AUpdate%20README.md%0A)

**Comment by ota-meshi** [comment]
Thanks for the PR.
However, I don't think a new description is needed in the README for this plugin. Because this plugin will lint `.astro` files but not `.ts` files. Thank you.

**Comment by skf-funzt** [comment]
Thanks, @ota-meshi, you're right.
Thanks for pointing that out :ok_hand:

**Comment by dwightgunning** [comment]
Glad I found this PR as I was stumped by this for more than a couple minutes too.

When it's pointed out that this plugin only targets '*.astro' files, it becomes quite obvious. I think it's easy to fall into the trap of thinking there's a problem with this plugin because the the Astro docs and the readme here discuss "astro components" (but not by file extension).
 
Some clarification in the Astro docs would be helpful. They encourage the use of the plugin, but don't mention that additional config for typescript is necessary.
- [Editor setup](https://docs.astro.build/en/editor-setup/#eslint)
- [Typescript guide](https://docs.astro.build/en/guides/typescript/)

**Comment by oanaOM** [comment]
@dwightgunning I had exactly the same experience and was struggling to make my eslint happy until I found this PR. I agree that it would be very helpful if this can be clarified in the docs. Are you happy to contribute with this?  😄

**Pull request closed without merging**
